version: '3'

services:

  app:
    environment:
      VIRTUAL_HOST: ${FRONTEND_HOST}
    networks:
      - default
      - nginx-proxy

  postgres:
    ports:
      - 50333:5432

networks:
  nginx-proxy:
    external: true
